vim.pack.add({ 'https://github.com/kndndrj/nvim-dbee' })
local key = require('utils.keymap')
key.map('n', ';dm', require('dbee').toggle, { desc = '[d]atabase [m]ode' })
-- require('dbee').install()
require('dbee').setup()
