# vim: ft=swayconfig

client.focused #143c52 #6a9060 #1a1a1a #90bcd0 #143c52
client.focused_inactive #2c4028 #96be8c #1a1a1a #3a5030 #2c4028
client.unfocused #2c4028 #add4a0 #1a1a1a #3a5030 #2c4028
client.pinned_focused #7a1e18 #2c4028 #add4a0 #c87868 #7a1e18

jump_labels_color #143c52FF
jump_labels_background #add4a0e6
jump_labels_scale 0.5
jump_labels_swallow true
