# vim: ft=swayconfig

client.focused #90bcd0 #6a9060 #1a1a1a #1e4868 #90bcd0
client.focused_inactive #2c4028 #96be8c #1a1a1a #3a5030 #2c4028
client.unfocused #2c4028 #add4a0 #1a1a1a #3a5030 #2c4028
client.pinned_focused #d8a8a0 #2c4028 #add4a0 #7a1e18 #d8a8a0

jump_labels_color #2a5c22FF
jump_labels_background #add4a0e6
jump_labels_scale 0.5
jump_labels_swallow true
