# vim: ft=swayconfig

client.focused #d4b85a #536053 #d0dcc8 #c8a870 #d4b85a
client.focused_inactive #6a7868 #2d382d #d0dcc8 #7aab72 #6a7868
client.unfocused #6a7868 #1a211a #d0dcc8 #7aab72 #6a7868
client.pinned_focused #c87868 #6a7868 #1a211a #402828 #c87868

jump_labels_color #d4b85aFF
jump_labels_background #1a211ae6
jump_labels_scale 0.5
jump_labels_swallow true
