env:
  TERM: xterm-256color

#  shell:
#  program: /bin/zsh
#  args:
#  - -l
#  - -c
#  - "tmux"

window:
  dimensions:
    columns: 100
    lines: 30
  padding:
    x: 3
    y: 3
  position:
    x: 130
    y: 70
  decorations: none
  dynamic_title: true
  opacity: 0.4

class:
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Normal
  bold:
    family: mononoki Nerd Font
    style: Bold
  italic:
    family: VictorMono Nerd Font
    style: Italic
  size: 16
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "#1a1a2e"
    foreground: "#e2d5bc"

  normal:
    black: "#bbbbbb"
    red: "#fb5c8e"
    green: "#84c49b"
    yellow: "#f6e08b"
    blue: "#f47d49"
    magenta: "#a29dff"
    cyan: "#93c5e6"
    white: "#f2f2f2"

  bright:
    black: "#bbbbbb"
    red: "#dd5289"
    green: "#9fd3b3"
    yellow: "#fff0b8"
    blue: "#f79f79"
    magenta: "#b2aeff"
    cyan: "#aed9f6"
    white: "#f2f2f2"

  dim:
    black: "#444444"
    red: "#e68ac1"
    green: "#cae7b9"
    yellow: "#fee074"
    blue: "#f79f79"
    magenta: "#565393"
    cyan: "#c4d1f5"
    white: "#f2f2f2"

mouse:
  hide_when_typing: false

selection:
  text: "0xffffff"
  background: "0xF34F4D"
  white: "0xffffff"
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

alt_send_esc: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

key_bindings:
  # Create a horizontal space
  - { key: Down, mods: Command | Alt, chars: "\x01\x22" }
  # Create a vertical space
  - { key: Right, mods: Command | Alt, chars: "\x01\x25" }
  # Move between spaces
  - { key: Right, mods: Control, chars: "\x0c" }
  - { key: Left, mods: Control, chars: "\x08" }
  - { key: Down, mods: Control, chars: "\x0a" }
  - { key: Up, mods: Control, chars: "\x0b" }
  # Move between Window
  - { key: PageDown, mods: Control, chars: "\x01\x6e" }
  - { key: PageUp, mods: Control, chars: "\x01\x70" }
  # Move between session
  - { key: PageUp, mods: Alt, chars: "\x01\x28" }
  - { key: PageDown, mods: Alt, chars: "\x01\x29" }
  # New Windows
  - { key: T, mods: Command, chars: "\x01\x63" }
  # Tab Windows
  - { key: Tab, mods: Control, chars: "\x01\x77" }
  # Close tmux
  - { key: W, mods: Alt, chars: "\x01\x78" }
  - {
      key: Q,
      mods: Control,
      chars: "tmux list-sessions | awk 'BEGIN{FS=\":\"}{print $1}' | xargs -n 1 tmux kill-session -t\n",
    }
  # tmux zoom
  - { key: Z, mods: Command, chars: "\x01\x7a" }
  # Save nvim Archive
  - { key: G, mods: Command, chars: "\x1b\x3a\x77\n" }
