--ozone-platform=wayland
--enable-features=AcceleratedVideoDecodeLinuxGL,WaylandWindowDecorations,WebUIDarkMode,WebRTCPipeWireCapturer
--force-dark-mode
--enable-zero-copy
--use-gl=egl
--ignore-gpu-blocklist
--start-maximized
