#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

function get_volume {
	wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}'
}

function send_notification {
    volume=$(get_volume)
    volume_integer=$(awk "BEGIN {printf \"%d\n\", $volume * 100}")

    if [ "$volume_integer" -eq 0 ]; then
        icon="audio-volume-muted"
    elif [ "$volume_integer" -le 33 ]; then
        icon="audio-volume-low"
    elif [ "$volume_integer" -le 66 ]; then
        icon="audio-volume-medium"
    else
        icon="audio-volume-high"
    fi

    notify-send -i "$icon" \
        -h int:value:$volume_integer \
        -h string:x-dunst-stack-tag:volume \
        "Volume"
}

case $1 in
up)
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ >/dev/null
	aplay ~/.config/dunst/vol.wav
	send_notification
	;;
down)
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%- >/dev/null
	aplay ~/.config/dunst/vol.wav
	send_notification
	;;
mute)
	# Toggle mute
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
	;;
esac
