daemonize
show-failed-attempts
clock
screenshot
effect-blur=15x15
effect-vignette=1:1
color=1a211a80
font="Inter"
indicator
indicator-radius=200
indicator-thickness=20
line-color=d0dcc8
ring-color=9aab94
inside-color=1a211a
key-hl-color=88b878
separator-color=00000000
text-color=d0dcc8
text-caps-lock-color=""
line-ver-color=6a94a8
ring-ver-color=6a94a8
inside-ver-color=1a211a
text-ver-color=d0dcc8
ring-wrong-color=c87868
text-wrong-color=c87868
inside-wrong-color=1a211a
inside-clear-color=1a211a
text-clear-color=d4b85a
ring-clear-color=d4b85a
line-clear-color=d0dcc8
line-wrong-color=d0dcc8
bs-hl-color=c87868
grace=2
grace-no-mouse
grace-no-touch
datestr=%a, %B %e
timestr=%I:%M %p
fade-in=0.3
ignore-empty-password
