daemonize
show-failed-attempts
clock
screenshot
effect-blur=15x15
effect-vignette=1:1
color=add4a080
font="SFPro Nerd Font Propo Text"
indicator
indicator-radius=200
indicator-thickness=20

# idle / typing
inside-color=add4a0
line-color=add4a0
ring-color=2a5c22
text-color=1a1a1a
key-hl-color=145850
bs-hl-color=7a1e18
separator-color=00000000

# verifying (blue)
inside-ver-color=add4a0
line-ver-color=add4a0
ring-ver-color=1e4868
text-ver-color=1a1a1a

# wrong (red)
inside-wrong-color=add4a0
line-wrong-color=add4a0
ring-wrong-color=7a1e18
text-wrong-color=7a1e18

# cleared (yellow)
inside-clear-color=add4a0
line-clear-color=add4a0
ring-clear-color=5a4808
text-clear-color=5a4808

# caps lock (magenta)
text-caps-lock-color=5a2858
caps-lock-key-hl-color=5a2858
caps-lock-bs-hl-color=7a1e18

grace=2
grace-no-mouse
grace-no-touch
datestr=%a, %B %e
timestr=%I:%M %p
fade-in=0.3
ignore-empty-password
