alias la = ls -la
alias ll = ls -l
alias ip = ip -color=auto
alias ping = prettyping
alias cp = cpx
alias tree = exa --icons --tree --level=4 --long --git
alias zt = /bin/zathura --fork
alias zb = zen-browser
alias lo = /bin/libreoffice
alias music = termusic
alias fm = yazi
alias update-grub = sudo grub-mkconfig -o /boot/grub/grub.cfg
alias neofetch = fastfetch -l ~/.config/fastfetch/thinkpad.txt --logo-color-1 white --logo-color-2 red --logo-color-3 '38;2;23;147;209'
alias gbc = git switch -c
alias grubc = sudo -e /etc/default/grub
alias kittyc = nvim ~/.config/kitty/kitty.conf
alias icat = kitten icat
alias s = kitten ssh
alias ssh = kitten ssh
alias tf = kitten transfer
alias vim = nvim
alias vimc = nvim ~/.config/nvim/init.lua
alias vimk = nvim ~/.config/nvim/lua/core/keymaps.lua
alias vimd = nvim ~/.config/nvim/lua/core/opts.lua
alias vima = nvim ~/.config/nvim/lua/core/autocmds.lua
alias viml = nvim ~/.config/nvim/lua/core/lsp.lua
alias newmc = nvim ~/.config/newm/config.py
alias hyprc = nvim ~/.config/hypr/hyprland.conf
alias scrollc = nvim ~/.config/scroll/config
alias keydc = nvim ~/Git/dotfiles/etc/keyd/default.conf
alias zshc = nvim ~/.zshrc
alias zshf = nvim ~/.zshfunc
alias zimc = nvim ~/.zimrc
alias dnsc = nvim /etc/resolv.conf
alias nftc = nvim /etc/nftables.conf
alias starshipc = nvim ~/.config/starship.toml
alias v = nvim
