;;; eyes-dark-theme.el --- Eyes (dark) — port del colorscheme nvim -*- lexical-binding: t; -*-
;;
;; Port directo de nvim/colors/eyes.lua (variante dark).
;; Paleta verde oscura para protección visual nocturna.

(deftheme eyes-dark
  "Dark variant of the eyes colorscheme (verde-bosque oscuro).
Calibrado para bajo contraste sin perder legibilidad.")

(let* ((c-bg0          "#1a211a")
       (c-bg1          "#202820")
       (c-bg2          "#263026")
       (c-bg3          "#2d382d")
       (c-bg4          "#3a463a")
       (c-bg5          "#536053")
       (c-fg0          "#d0dcc8")
       (c-fg1          "#b8c8b0")
       (c-fg2          "#9aab94")
       (c-green0       "#7aab72")
       (c-green1       "#88b878")
       (c-green2       "#6a9460")
       (c-teal         "#5ab8a8")
       (c-blue0        "#6a94a8")
       (c-blue1        "#82aab8")
       (c-violet       "#9090b8")
       (c-aqua         "#6ab8b0")
       (c-orange0      "#b89a6a")
       (c-orange1      "#c8a870")
       (c-red          "#c87868")
       (c-yellow       "#d4b85a")
       (c-pink         "#b890b0")
       (c-ash          "#7a8c72")
       (c-gray0        "#8a9a88")
       (c-gray1        "#7a8a78")
       (c-gray2        "#6a7868")
       (c-winterGreen  "#243224")
       (c-winterBlue   "#223040")
       (c-winterRed    "#402828")
       (c-winterYellow "#3a3420"))

  (custom-theme-set-faces
   'eyes-dark

   ;; ---------- Base UI ----------
   `(default                       ((t (:background ,c-bg0 :foreground ,c-fg0))))
   `(cursor                        ((t (:background ,c-fg0 :foreground ,c-bg0))))
   `(fringe                        ((t (:background ,c-bg0 :foreground ,c-gray2))))
   `(vertical-border               ((t (:foreground ,c-bg4))))
   `(window-divider                ((t (:foreground ,c-bg4))))
   `(window-divider-first-pixel    ((t (:foreground ,c-bg4))))
   `(window-divider-last-pixel     ((t (:foreground ,c-bg4))))
   `(hl-line                       ((t (:background ,c-bg2))))
   `(highlight                     ((t (:background ,c-bg3))))
   `(region                        ((t (:background ,c-bg4))))
   `(secondary-selection           ((t (:background ,c-bg3))))
   `(lazy-highlight                ((t (:background ,c-bg3))))
   `(isearch                       ((t (:background ,c-yellow :foreground ,c-bg0 :weight bold))))
   `(isearch-fail                  ((t (:background ,c-winterRed :foreground ,c-red))))
   `(match                         ((t (:background ,c-bg4))))
   `(show-paren-match              ((t (:background ,c-bg4 :weight bold))))
   `(show-paren-mismatch           ((t (:background ,c-red :foreground ,c-bg0))))
   `(trailing-whitespace           ((t (:background ,c-winterRed))))
   `(whitespace-trailing           ((t (:background ,c-winterRed))))
   `(whitespace-tab                ((t (:foreground ,c-bg4))))
   `(whitespace-space              ((t (:foreground ,c-bg4))))
   `(whitespace-newline            ((t (:foreground ,c-bg4))))
   `(fill-column-indicator         ((t (:foreground ,c-bg4))))
   `(line-number                   ((t (:background ,c-bg0 :foreground ,c-bg5))))
   `(line-number-current-line      ((t (:background ,c-bg2 :foreground ,c-gray0 :weight bold))))
   `(link                          ((t (:foreground ,c-blue0 :underline t))))
   `(link-visited                  ((t (:foreground ,c-violet :underline t))))
   `(shadow                        ((t (:foreground ,c-ash))))
   `(error                         ((t (:foreground ,c-red))))
   `(warning                       ((t (:foreground ,c-yellow))))
   `(success                       ((t (:foreground ,c-green0))))

   ;; ---------- Modeline / header ----------
   `(mode-line                     ((t (:background ,c-bg3 :foreground ,c-fg1))))
   `(mode-line-active              ((t (:background ,c-bg3 :foreground ,c-fg1))))
   `(mode-line-inactive            ((t (:background ,c-bg2 :foreground ,c-bg5))))
   `(mode-line-highlight           ((t (:background ,c-bg4))))
   `(mode-line-emphasis            ((t (:foreground ,c-red :weight bold))))
   `(mode-line-buffer-id           ((t (:foreground ,c-fg0 :weight bold))))
   `(header-line                   ((t (:background ,c-bg1 :foreground ,c-fg1))))
   `(header-line-highlight         ((t (:background ,c-bg3))))

   ;; ---------- Minibuffer ----------
   `(minibuffer-prompt             ((t (:foreground ,c-blue0 :weight bold))))
   `(completions-common-part       ((t (:foreground ,c-blue0 :weight bold))))
   `(completions-first-difference  ((t (:foreground ,c-red :weight bold))))
   `(completions-annotations       ((t (:foreground ,c-ash :slant italic))))

   ;; ---------- Tab-line / tab-bar ----------
   `(tab-bar                       ((t (:background ,c-bg5 :foreground ,c-fg1))))
   `(tab-bar-tab                   ((t (:background ,c-bg3 :foreground ,c-fg1 :weight bold))))
   `(tab-bar-tab-inactive          ((t (:background ,c-bg2 :foreground ,c-bg5))))
   `(tab-line                      ((t (:background ,c-bg5 :foreground ,c-fg1))))

   ;; ---------- Font-lock (syntax) ----------
   `(font-lock-comment-face            ((t (:foreground ,c-ash :slant italic))))
   `(font-lock-comment-delimiter-face  ((t (:foreground ,c-ash :slant italic))))
   `(font-lock-doc-face                ((t (:foreground ,c-green0 :slant italic))))
   `(font-lock-doc-markup-face         ((t (:foreground ,c-teal))))
   `(font-lock-string-face             ((t (:foreground ,c-green1))))
   `(font-lock-constant-face           ((t (:foreground ,c-orange0))))
   `(font-lock-number-face             ((t (:foreground ,c-pink))))
   `(font-lock-keyword-face            ((t (:foreground ,c-violet :slant italic))))
   `(font-lock-builtin-face            ((t (:foreground ,c-red))))
   `(font-lock-function-name-face      ((t (:foreground ,c-blue1))))
   `(font-lock-function-call-face      ((t (:foreground ,c-blue1))))
   `(font-lock-variable-name-face      ((t (:foreground ,c-fg0))))
   `(font-lock-variable-use-face       ((t (:foreground ,c-fg0))))
   `(font-lock-type-face               ((t (:foreground ,c-aqua))))
   `(font-lock-preprocessor-face       ((t (:foreground ,c-red))))
   `(font-lock-warning-face            ((t (:foreground ,c-yellow))))
   `(font-lock-negation-char-face      ((t (:foreground ,c-teal))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,c-orange0 :weight bold))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,c-orange0))))
   `(font-lock-property-name-face      ((t (:foreground ,c-green1))))
   `(font-lock-property-use-face       ((t (:foreground ,c-green1))))
   `(font-lock-operator-face           ((t (:foreground ,c-teal))))
   `(font-lock-punctuation-face        ((t (:foreground ,c-gray1))))
   `(font-lock-delimiter-face          ((t (:foreground ,c-gray1))))
   `(font-lock-bracket-face            ((t (:foreground ,c-gray1))))
   `(font-lock-misc-punctuation-face   ((t (:foreground ,c-gray1))))
   `(font-lock-escape-face             ((t (:foreground ,c-orange0))))

   ;; ---------- Treesit faces (Emacs 29+) ----------
   ;; Faces estándar que el motor `treesit-font-lock-feature-list` activa
   ;; en nivel 4. Replican capturas @* equivalentes de nvim/colors/eyes.lua.
   `(treesit-fontification-error-face  ((t (:foreground ,c-red :underline t))))
   `(font-lock-regexp-face             ((t (:foreground ,c-orange0))))

   ;; ---------- Eyes custom faces (semantic tokens + treesit granular) ----------
   `(eyes-parameter-face   ((t (:foreground ,c-orange1 :slant italic))))
   `(eyes-member-face      ((t (:foreground ,c-green1))))
   `(eyes-namespace-face   ((t (:foreground ,c-orange0))))
   `(eyes-macro-face       ((t (:foreground ,c-pink))))
   `(eyes-decorator-face   ((t (:foreground ,c-pink :slant italic))))
   `(eyes-constructor-face ((t (:foreground ,c-teal))))
   `(eyes-module-face      ((t (:foreground ,c-orange0))))
   `(eyes-return-face      ((t (:foreground ,c-red))))
   `(eyes-exception-face   ((t (:foreground ,c-red :weight bold))))
   `(eyes-import-face      ((t (:foreground ,c-red))))
   `(eyes-keyword-op-face  ((t (:foreground ,c-teal :weight bold))))

   ;; ---------- Evil ----------
   `(evil-ex-info                  ((t (:foreground ,c-green2 :weight bold))))
   `(evil-ex-substitute-matches    ((t (:background ,c-bg3 :foreground ,c-fg0))))
   `(evil-ex-substitute-replacement ((t (:background ,c-violet :foreground ,c-bg0))))
   `(evil-ex-search                ((t (:background ,c-yellow :foreground ,c-bg0))))

   ;; ---------- evil-goggles ----------
   `(evil-goggles-default-face     ((t (:background ,c-bg3))))
   `(evil-goggles-yank-face        ((t (:background ,c-yellow :foreground ,c-bg0))))
   `(evil-goggles-delete-face      ((t (:background ,c-winterRed :foreground ,c-red))))
   `(evil-goggles-change-face      ((t (:background ,c-winterBlue))))
   `(evil-goggles-paste-face       ((t (:background ,c-winterGreen))))

   ;; ---------- Diff / Magit ----------
   `(diff-added                    ((t (:background ,c-winterGreen :foreground ,c-green0))))
   `(diff-removed                  ((t (:background ,c-winterRed   :foreground ,c-red))))
   `(diff-changed                  ((t (:background ,c-winterBlue  :foreground ,c-yellow))))
   `(diff-context                  ((t (:foreground ,c-fg2))))
   `(diff-header                   ((t (:foreground ,c-blue1 :weight bold))))
   `(diff-file-header              ((t (:foreground ,c-fg0 :weight bold))))
   `(diff-hunk-header              ((t (:foreground ,c-teal :weight bold))))
   `(diff-refine-added             ((t (:background ,c-green0 :foreground ,c-bg0))))
   `(diff-refine-removed           ((t (:background ,c-red :foreground ,c-bg0))))
   `(diff-refine-changed           ((t (:background ,c-yellow :foreground ,c-bg0))))

   `(magit-diff-added              ((t (:background ,c-winterGreen :foreground ,c-green0))))
   `(magit-diff-added-highlight    ((t (:background ,c-winterGreen :foreground ,c-green0 :weight bold))))
   `(magit-diff-removed            ((t (:background ,c-winterRed :foreground ,c-red))))
   `(magit-diff-removed-highlight  ((t (:background ,c-winterRed :foreground ,c-red :weight bold))))
   `(magit-diff-context            ((t (:foreground ,c-fg2))))
   `(magit-diff-context-highlight  ((t (:background ,c-bg1 :foreground ,c-fg1))))
   `(magit-diff-hunk-heading           ((t (:background ,c-bg3 :foreground ,c-teal))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,c-bg4 :foreground ,c-teal :weight bold))))
   `(magit-diff-file-heading           ((t (:foreground ,c-fg0 :weight bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,c-bg2 :foreground ,c-fg0 :weight bold))))
   `(magit-section-heading             ((t (:foreground ,c-blue1 :weight bold))))
   `(magit-section-highlight           ((t (:background ,c-bg1))))
   `(magit-branch-local                ((t (:foreground ,c-blue0 :weight bold))))
   `(magit-branch-remote               ((t (:foreground ,c-green0 :weight bold))))
   `(magit-branch-current              ((t (:foreground ,c-red :weight bold :box t))))
   `(magit-hash                        ((t (:foreground ,c-ash))))
   `(magit-tag                         ((t (:foreground ,c-orange0))))
   `(magit-log-author                  ((t (:foreground ,c-blue1))))
   `(magit-log-date                    ((t (:foreground ,c-ash))))
   `(magit-log-graph                   ((t (:foreground ,c-bg5))))

   ;; ---------- git-gutter / diff-hl ----------
   `(git-gutter:added              ((t (:foreground ,c-green1))))
   `(git-gutter:modified           ((t (:foreground ,c-yellow))))
   `(git-gutter:deleted            ((t (:foreground ,c-red))))
   `(diff-hl-insert                ((t (:background ,c-bg0 :foreground ,c-green1))))
   `(diff-hl-change                ((t (:background ,c-bg0 :foreground ,c-yellow))))
   `(diff-hl-delete                ((t (:background ,c-bg0 :foreground ,c-red))))

   ;; ---------- Org-mode ----------
   `(org-level-1                   ((t (:foreground ,c-blue0 :weight bold :height 1.15))))
   `(org-level-2                   ((t (:foreground ,c-blue1 :weight bold :height 1.10))))
   `(org-level-3                   ((t (:foreground ,c-teal  :weight bold :height 1.05))))
   `(org-level-4                   ((t (:foreground ,c-green2 :weight bold))))
   `(org-level-5                   ((t (:foreground ,c-violet :weight bold))))
   `(org-level-6                   ((t (:foreground ,c-aqua :weight bold))))
   `(org-level-7                   ((t (:foreground ,c-pink :weight bold))))
   `(org-level-8                   ((t (:foreground ,c-orange0 :weight bold))))
   `(org-document-title            ((t (:foreground ,c-blue0 :weight bold :height 1.3))))
   `(org-document-info             ((t (:foreground ,c-fg2))))
   `(org-document-info-keyword     ((t (:foreground ,c-ash))))
   `(org-meta-line                 ((t (:foreground ,c-ash :slant italic))))
   `(org-block                     ((t (:background ,c-bg1 :foreground ,c-fg0 :extend t))))
   `(org-block-begin-line          ((t (:background ,c-bg2 :foreground ,c-ash :extend t))))
   `(org-block-end-line            ((t (:background ,c-bg2 :foreground ,c-ash :extend t))))
   `(org-code                      ((t (:background ,c-bg1 :foreground ,c-green1))))
   `(org-verbatim                  ((t (:foreground ,c-green1))))
   `(org-quote                     ((t (:foreground ,c-fg2 :slant italic))))
   `(org-link                      ((t (:foreground ,c-blue0 :underline t))))
   `(org-footnote                  ((t (:foreground ,c-aqua :underline t))))
   `(org-table                     ((t (:foreground ,c-fg1))))
   `(org-todo                      ((t (:foreground ,c-red :weight bold))))
   `(org-done                      ((t (:foreground ,c-green0 :weight bold))))
   `(org-headline-done             ((t (:foreground ,c-ash :strike-through t))))
   `(org-tag                       ((t (:foreground ,c-violet :weight bold))))
   `(org-priority                  ((t (:foreground ,c-orange0 :weight bold))))
   `(org-date                      ((t (:foreground ,c-aqua :underline t))))
   `(org-special-keyword           ((t (:foreground ,c-orange0))))
   `(org-checkbox                  ((t (:foreground ,c-teal :weight bold))))

   ;; ---------- Markdown ----------
   `(markdown-header-face-1        ((t (:foreground ,c-blue0 :weight bold :height 1.15))))
   `(markdown-header-face-2        ((t (:foreground ,c-blue1 :weight bold :height 1.10))))
   `(markdown-header-face-3        ((t (:foreground ,c-teal  :weight bold :height 1.05))))
   `(markdown-header-face-4        ((t (:foreground ,c-green2 :weight bold))))
   `(markdown-header-face-5        ((t (:foreground ,c-violet :weight bold))))
   `(markdown-header-face-6        ((t (:foreground ,c-aqua :weight bold))))
   `(markdown-header-delimiter-face ((t (:foreground ,c-gray1))))
   `(markdown-bold-face            ((t (:weight bold))))
   `(markdown-italic-face          ((t (:slant italic))))
   `(markdown-code-face            ((t (:background ,c-bg1 :foreground ,c-green1))))
   `(markdown-inline-code-face     ((t (:background ,c-bg1 :foreground ,c-green1))))
   `(markdown-pre-face             ((t (:background ,c-bg1 :foreground ,c-green1))))
   `(markdown-link-face            ((t (:foreground ,c-blue0 :underline t))))
   `(markdown-url-face             ((t (:foreground ,c-green1))))
   `(markdown-list-face            ((t (:foreground ,c-teal))))
   `(markdown-blockquote-face      ((t (:foreground ,c-fg2 :slant italic))))
   `(markdown-language-keyword-face ((t (:foreground ,c-orange0))))

   ;; ---------- Vertico / Consult / Corfu ----------
   `(vertico-current               ((t (:background ,c-bg4 :weight bold :extend t))))
   `(vertico-group-title           ((t (:foreground ,c-blue0 :weight bold))))
   `(vertico-group-separator       ((t (:foreground ,c-bg5))))
   `(consult-file                  ((t (:foreground ,c-blue1))))
   `(consult-line-number           ((t (:foreground ,c-ash))))
   `(consult-preview-line          ((t (:background ,c-bg2))))
   `(consult-preview-match         ((t (:background ,c-yellow :foreground ,c-bg0))))
   `(corfu-default                 ((t (:background ,c-bg3 :foreground ,c-fg1))))
   `(corfu-current                 ((t (:background ,c-bg4 :weight bold))))
   `(corfu-bar                     ((t (:background ,c-bg5))))
   `(corfu-border                  ((t (:background ,c-bg5))))
   `(marginalia-key                ((t (:foreground ,c-red))))
   `(marginalia-documentation      ((t (:foreground ,c-ash :slant italic))))
   `(orderless-match-face-0        ((t (:foreground ,c-blue0 :weight bold))))
   `(orderless-match-face-1        ((t (:foreground ,c-violet :weight bold))))
   `(orderless-match-face-2        ((t (:foreground ,c-orange0 :weight bold))))
   `(orderless-match-face-3        ((t (:foreground ,c-teal :weight bold))))

   ;; ---------- Company ----------
   `(company-tooltip               ((t (:background ,c-bg3 :foreground ,c-fg1))))
   `(company-tooltip-selection     ((t (:background ,c-bg4 :foreground ,c-fg0 :weight bold))))
   `(company-tooltip-common        ((t (:foreground ,c-red :weight bold))))
   `(company-tooltip-annotation    ((t (:foreground ,c-ash :slant italic))))
   `(company-scrollbar-bg          ((t (:background ,c-bg4))))
   `(company-scrollbar-fg          ((t (:background ,c-bg5))))

   ;; ---------- Which-key ----------
   `(which-key-key-face                       ((t (:foreground ,c-red :weight bold))))
   `(which-key-group-description-face         ((t (:foreground ,c-violet :weight bold))))
   `(which-key-command-description-face       ((t (:foreground ,c-fg0))))
   `(which-key-local-map-description-face     ((t (:foreground ,c-blue1))))
   `(which-key-separator-face                 ((t (:foreground ,c-ash))))
   `(which-key-special-key-face               ((t (:foreground ,c-teal))))

   ;; ---------- Flymake / Flycheck ----------
   `(flymake-error                 ((t (:underline (:style wave :color ,c-red)))))
   `(flymake-warning               ((t (:underline (:style wave :color ,c-yellow)))))
   `(flymake-note                  ((t (:underline (:style wave :color ,c-aqua)))))
   `(flycheck-error                ((t (:underline (:style wave :color ,c-red)))))
   `(flycheck-warning              ((t (:underline (:style wave :color ,c-yellow)))))
   `(flycheck-info                 ((t (:underline (:style wave :color ,c-aqua)))))
   `(flycheck-fringe-error         ((t (:foreground ,c-red))))
   `(flycheck-fringe-warning       ((t (:foreground ,c-yellow))))
   `(flycheck-fringe-info          ((t (:foreground ,c-aqua))))
   `(flyspell-incorrect            ((t (:underline (:style wave :color ,c-red)))))

   ;; ---------- LSP / Eglot ----------
   `(eglot-highlight-symbol-face   ((t (:background ,c-winterYellow))))
   `(eglot-mode-line               ((t (:foreground ,c-teal :weight bold))))
   `(lsp-face-highlight-textual    ((t (:background ,c-winterYellow))))
   `(lsp-face-highlight-read       ((t (:background ,c-winterYellow))))
   `(lsp-face-highlight-write      ((t (:background ,c-winterYellow :underline t))))
   `(lsp-headerline-breadcrumb-path-face         ((t (:foreground ,c-ash))))
   `(lsp-headerline-breadcrumb-symbols-face      ((t (:foreground ,c-blue1 :weight bold))))
   `(lsp-ui-doc-background         ((t (:background ,c-bg1))))
   `(lsp-ui-doc-border             ((t (:foreground ,c-bg5))))

   `(eldoc-highlight-function-argument ((t (:foreground ,c-yellow :weight bold))))

   ;; ---------- Dired ----------
   `(dired-directory               ((t (:foreground ,c-blue1 :weight bold))))
   `(dired-symlink                 ((t (:foreground ,c-aqua :slant italic))))
   `(dired-broken-symlink          ((t (:background ,c-red :foreground ,c-bg0))))
   `(dired-header                  ((t (:foreground ,c-blue0 :weight bold))))
   `(dired-mark                    ((t (:foreground ,c-red :weight bold))))
   `(dired-marked                  ((t (:foreground ,c-orange0 :weight bold))))
   `(dired-flagged                 ((t (:foreground ,c-red :weight bold))))
   `(dired-perm-write              ((t (:foreground ,c-yellow))))
   `(dired-special                 ((t (:foreground ,c-pink))))
   `(dired-ignored                 ((t (:foreground ,c-ash))))

   ;; ---------- Treemacs ----------
   `(treemacs-directory-face       ((t (:foreground ,c-blue1 :weight bold))))
   `(treemacs-file-face            ((t (:foreground ,c-fg0))))
   `(treemacs-root-face            ((t (:foreground ,c-blue0 :weight bold :height 1.1))))
   `(treemacs-git-modified-face    ((t (:foreground ,c-yellow))))
   `(treemacs-git-added-face       ((t (:foreground ,c-green1))))
   `(treemacs-git-untracked-face   ((t (:foreground ,c-aqua))))
   `(treemacs-git-renamed-face     ((t (:foreground ,c-violet))))
   `(treemacs-git-ignored-face     ((t (:foreground ,c-ash))))

   ;; ---------- Doom-modeline / Doom-themes / solaire ----------
   `(doom-modeline-buffer-file              ((t (:foreground ,c-fg0 :weight bold))))
   `(doom-modeline-buffer-modified          ((t (:foreground ,c-red :weight bold))))
   `(doom-modeline-buffer-major-mode        ((t (:foreground ,c-teal :weight bold))))
   `(doom-modeline-buffer-path              ((t (:foreground ,c-blue1))))
   `(doom-modeline-buffer-project-root      ((t (:foreground ,c-blue0 :weight bold))))
   `(doom-modeline-project-dir              ((t (:foreground ,c-blue0 :weight bold))))
   `(doom-modeline-info                     ((t (:foreground ,c-green0 :weight bold))))
   `(doom-modeline-warning                  ((t (:foreground ,c-yellow :weight bold))))
   `(doom-modeline-urgent                   ((t (:foreground ,c-red :weight bold))))
   `(doom-modeline-debug                    ((t (:foreground ,c-aqua))))
   `(doom-modeline-evil-normal-state        ((t (:foreground ,c-green0 :weight bold))))
   `(doom-modeline-evil-insert-state        ((t (:foreground ,c-red :weight bold))))
   `(doom-modeline-evil-visual-state        ((t (:foreground ,c-violet :weight bold))))
   `(doom-modeline-evil-replace-state       ((t (:foreground ,c-orange0 :weight bold))))
   `(doom-modeline-evil-motion-state        ((t (:foreground ,c-teal :weight bold))))
   `(doom-modeline-evil-operator-state      ((t (:foreground ,c-blue0 :weight bold))))
   `(doom-modeline-lsp-success              ((t (:foreground ,c-green0))))
   `(doom-modeline-lsp-warning              ((t (:foreground ,c-yellow))))
   `(doom-modeline-lsp-error                ((t (:foreground ,c-red))))
   `(doom-modeline-bar                      ((t (:background ,c-teal))))
   `(doom-modeline-bar-inactive             ((t (:background ,c-bg2))))
   `(doom-dashboard-banner                  ((t (:foreground ,c-blue0 :weight bold))))
   `(doom-dashboard-menu-title              ((t (:foreground ,c-fg0 :weight bold))))
   `(doom-dashboard-menu-desc               ((t (:foreground ,c-blue1))))
   `(doom-dashboard-footer                  ((t (:foreground ,c-ash :slant italic))))
   `(doom-dashboard-footer-icon             ((t (:foreground ,c-yellow))))
   `(solaire-default-face                   ((t (:background ,c-bg1 :foreground ,c-fg0))))
   `(solaire-hl-line-face                   ((t (:background ,c-bg3))))
   `(solaire-line-number-face               ((t (:background ,c-bg1 :foreground ,c-bg5))))
   `(solaire-mode-line-face                 ((t (:background ,c-bg2 :foreground ,c-fg1))))
   `(solaire-mode-line-inactive-face        ((t (:background ,c-bg1 :foreground ,c-bg5))))

   ;; ---------- Highlight indent guides ----------
   `(highlight-indent-guides-character-face ((t (:foreground ,c-bg4))))
   `(highlight-indent-guides-top-character-face ((t (:foreground ,c-bg5))))

   ;; ---------- popup / posframe ----------
   `(popup-face                    ((t (:background ,c-bg3 :foreground ,c-fg1))))
   `(popup-tip-face                ((t (:background ,c-bg1 :foreground ,c-fg0))))
   `(popup-menu-selection-face     ((t (:background ,c-bg4 :foreground ,c-fg0 :weight bold))))
   `(posframe-border               ((t (:background ,c-bg5))))

   ;; ---------- transient (magit/forge) ----------
   `(transient-heading             ((t (:foreground ,c-blue0 :weight bold))))
   `(transient-key                 ((t (:foreground ,c-red :weight bold))))
   `(transient-argument            ((t (:foreground ,c-orange0 :weight bold))))
   `(transient-value               ((t (:foreground ,c-violet))))

   ;; ---------- hl-todo ----------
   `(hl-todo                       ((t (:background ,c-blue0 :foreground ,c-bg0 :weight bold))))

   ;; ---------- DAP UI ----------
   `(dap-ui-breakpoint-verified-fringe ((t (:foreground ,c-red))))
   `(dap-ui-pending-breakpoint-face    ((t (:foreground ,c-yellow))))
   `(dap-ui-locals-scope-face          ((t (:foreground ,c-teal :weight bold))))
   `(dap-ui-locals-variable-face       ((t (:foreground ,c-fg0))))
   `(dap-ui-locals-value-face          ((t (:foreground ,c-orange0))))

   ;; ---------- Tree-sitter ----------
   `(tree-sitter-hl-face:function          ((t (:foreground ,c-blue1))))
   `(tree-sitter-hl-face:function.call     ((t (:foreground ,c-blue1))))
   `(tree-sitter-hl-face:function.builtin  ((t (:foreground ,c-red))))
   `(tree-sitter-hl-face:keyword           ((t (:foreground ,c-violet :slant italic))))
   `(tree-sitter-hl-face:type              ((t (:foreground ,c-aqua))))
   `(tree-sitter-hl-face:type.builtin      ((t (:foreground ,c-aqua :weight bold))))
   `(tree-sitter-hl-face:string            ((t (:foreground ,c-green1))))
   `(tree-sitter-hl-face:string.special    ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:constant          ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:number            ((t (:foreground ,c-pink))))
   `(tree-sitter-hl-face:operator          ((t (:foreground ,c-teal))))
   `(tree-sitter-hl-face:comment           ((t (:foreground ,c-ash :slant italic))))
   `(tree-sitter-hl-face:variable          ((t (:foreground ,c-fg0))))
   `(tree-sitter-hl-face:variable.builtin  ((t (:foreground ,c-red))))
   `(tree-sitter-hl-face:property          ((t (:foreground ,c-green1))))
   `(tree-sitter-hl-face:property.definition ((t (:foreground ,c-green1))))
   `(tree-sitter-hl-face:constructor       ((t (:foreground ,c-teal))))
   `(tree-sitter-hl-face:module            ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:namespace         ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:attribute         ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:keyword.return    ((t (:foreground ,c-red))))
   `(tree-sitter-hl-face:keyword.exception ((t (:foreground ,c-red :weight bold))))
   `(tree-sitter-hl-face:keyword.import    ((t (:foreground ,c-red))))
   `(tree-sitter-hl-face:keyword.operator  ((t (:foreground ,c-teal :weight bold))))
   `(tree-sitter-hl-face:keyword.function  ((t (:foreground ,c-violet :slant italic))))
   `(tree-sitter-hl-face:variable.parameter ((t (:foreground ,c-orange1 :slant italic))))
   `(tree-sitter-hl-face:variable.member   ((t (:foreground ,c-green1))))
   `(tree-sitter-hl-face:variable.special  ((t (:foreground ,c-red))))
   `(tree-sitter-hl-face:function.macro    ((t (:foreground ,c-pink))))
   `(tree-sitter-hl-face:function.method   ((t (:foreground ,c-blue1))))
   `(tree-sitter-hl-face:function.method.call ((t (:foreground ,c-blue1))))
   `(tree-sitter-hl-face:string.escape     ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:string.regexp     ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:string.special    ((t (:foreground ,c-orange0))))
   `(tree-sitter-hl-face:punctuation       ((t (:foreground ,c-gray1))))
   `(tree-sitter-hl-face:punctuation.bracket ((t (:foreground ,c-gray1))))
   `(tree-sitter-hl-face:punctuation.delimiter ((t (:foreground ,c-gray1))))
   `(tree-sitter-hl-face:punctuation.special ((t (:foreground ,c-teal))))
   `(tree-sitter-hl-face:tag               ((t (:foreground ,c-blue0))))
   `(tree-sitter-hl-face:tag.attribute     ((t (:foreground ,c-fg0))))
   `(tree-sitter-hl-face:tag.delimiter     ((t (:foreground ,c-gray1))))
   `(tree-sitter-hl-face:doc                ((t (:foreground ,c-green0 :slant italic))))
   `(tree-sitter-hl-face:embedded          ((t (:foreground ,c-fg0))))
   `(tree-sitter-hl-face:label             ((t (:foreground ,c-pink))))
   `(tree-sitter-hl-face:markup.bold       ((t (:weight bold))))
   `(tree-sitter-hl-face:markup.italic     ((t (:slant italic))))
   `(tree-sitter-hl-face:markup.link       ((t (:foreground ,c-blue0 :underline t))))
   `(tree-sitter-hl-face:markup.link.url   ((t (:foreground ,c-green1 :underline t))))
   `(tree-sitter-hl-face:markup.heading    ((t (:foreground ,c-blue0 :weight bold))))
   `(tree-sitter-hl-face:markup.list       ((t (:foreground ,c-teal))))
   `(tree-sitter-hl-face:markup.raw        ((t (:foreground ,c-green1)))))

  (custom-theme-set-variables
   'eyes-dark
   `(ansi-color-names-vector
     [,c-bg0 ,c-red ,c-green1 ,c-yellow ,c-blue1 ,c-pink ,c-aqua ,c-fg1])
   `(rustic-ansi-faces
     [,c-bg0 ,c-red ,c-green1 ,c-yellow ,c-blue1 ,c-pink ,c-aqua ,c-fg1])))

(provide-theme 'eyes-dark)
;;; eyes-dark-theme.el ends here
