code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension adrianwilczynski.namespace
code --install-extension Catppuccin.catppuccin-vsc
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension FranciscoBach.miramare
code --install-extension Gruntfuggly.activitusbar
code --install-extension jbhannah.autopairs-code
code --install-extension jorgeserrano.vscode-csharp-snippets
code --install-extension k--kato.docomment
code --install-extension kreativ-software.csharpextensions
code --install-extension ms-dotnettools.csharp
code --install-extension patcx.vscode-nuget-gallery
code --install-extension Prodam.netcore-extension-pack
code --install-extension sreetamd.karma
code --install-extension usernamehw.errorlens
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
