code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension aguilar.miramare
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension alexisvt.flutter-snippets
code --install-extension batisteo.vscode-django
code --install-extension BeardedBear.beardedtheme
code --install-extension bungcip.better-toml
code --install-extension cargo-inspect-vscode.cargo-inspect
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension dongli.python-preview
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-extension-pack
code --install-extension DotJoshJohnson.xml
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension everettjf.pubspec-dependency-search
code --install-extension formulahendry.code-runner
code --install-extension Gruntfuggly.activitusbar
code --install-extension hbenl.vscode-test-explorer
code --install-extension helgardrichard.helium-icon-theme
code --install-extension jakebathman.mysql-syntax
code --install-extension JakeBecker.elixir-ls
code --install-extension jeff-hykin.better-c-syntax
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jeff-hykin.better-dockerfile-syntax
code --install-extension jeff-hykin.better-shellscript-syntax
code --install-extension kevinkassimo.cargo-toml-snippets
code --install-extension KevinRose.vsc-python-indent
code --install-extension ldd-vs-code.better-package-json
code --install-extension magicstack.MagicPython
code --install-extension marcelovelasquez.flutter-tree
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension mkxml.vscode-filesize
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-es
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension Nash.awesome-flutter-snippets
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension njqdev.vscode-python-typehint
code --install-extension Olliebrown.pyside2-vsc
code --install-extension oscarcs.dart-syntax-highlighting-only
code --install-extension panicbit.cargo
code --install-extension pflannery.vscode-versionlens
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension samuelcolvin.jinjahtml
code --install-extension scala-lang.scala
code --install-extension sreetamd.karma
code --install-extension TabNine.tabnine-vscode
code --install-extension tushortz.java-imports-snippets
code --install-extension usernamehw.errorlens
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wholroyd.jinja
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension zhoufeng.pyqt-integration
