local fn = require('utils.fn')

require('plugins.ui.treesitter')
vim.pack.add({ 'https://github.com/MunifTanjim/nui.nvim' })
fn.lazy_load('UIEnter', 'catppuccin', function()
  require('plugins.ui.catppuccin')
  require('plugins.ui.base')
  require('plugins.ui.noice')
  require('plugins.ui.gitsigns')
end)
