local fn = require('utils.fn')
fn.lazy_load('CursorMoved', 'nvim-surround', function()
  vim.pack.add({ { src = 'https://github.com/chaoren/vim-wordmotion' } })
  vim.pack.add({ { src = 'https://github.com/kylechui/nvim-surround' } })
  require('nvim-surround').setup({})
end)

require('plugins.general.pickers')

fn.lazy_load('InsertEnter', 'ultimate-autopair', function()
  require('plugins.general.autopair')
end)
require('plugins.general.harpoon')
require('plugins.general.mini')
require('plugins.general.search_and_replace')
