return {
  {
    event = "InsertEnter",
    "m4xshen/autoclose.nvim",
    config = true,
  },
  {
    "echasnovski/mini.splitjoin",
    version = false,
    keys = { { "gS" } },
    config = function()
      require("mini.splitjoin").setup()
    end,
  },
  -- {
  --   "wellle/targets.vim",
  --   keys = {
  --     { "ci" },
  --     { "di" },
  --     { "yi" },
  --     { "cI" },
  --     { "dI" },
  --     { "yI" },
  --     { "ca" },
  --     { "da" },
  --     { "ya" },
  --     { "cA" },
  --     { "dA" },
  --     { "yA" },
  --   },
  -- },
  {
    "echasnovski/mini.ai",
    version = false,
    keys = {
      { "ci" },
      { "di" },
      { "yi" },
      { "cI" },
      { "dI" },
      { "yI" },
      { "ca" },
      { "da" },
      { "ya" },
      { "cA" },
      { "dA" },
      { "yA" },
    },
    config = function()
      require("mini.ai").setup()
    end,
  },
  {
    "chaoren/vim-wordmotion",
    keys = {
      { "w" },
      { "W" },
      { "b" },
      { "B" },
      { "e" },
      { "E" },
      { "ge" },
      { "gE" },
      { "caw" },
      { "caW" },
      { "ciw" },
      { "ciW" },
      { "daw" },
      { "daW" },
      { "diw" },
      { "diW" },
      { "yaw" },
      { "daW" },
      { "yiw" },
      { "yiW" },
    },
  },
  {
    "kylechui/nvim-surround",
    keys = { { "cs" }, { "ds" }, { "ys" } },
    config = true,
  },
}
