# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#143c52" }

# Find
find_keyword  = { fg = "#7a4a18", bold = true, italic = true, underline = true }
find_position = { fg = "#5a2858", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#2a5c22", bg = "#2a5c22" }
marker_cut      = { fg = "#7a1e18", bg = "#7a1e18" }
marker_marked   = { fg = "#143c52", bg = "#143c52" }
marker_selected = { fg = "#7a4a18", bg = "#7a4a18" }

# Count
count_copied   = { fg = "#add4a0", bg = "#2a5c22" }
count_cut      = { fg = "#add4a0", bg = "#7a1e18" }
count_selected = { fg = "#add4a0", bg = "#7a4a18" }

# Border
border_symbol = "│"
border_style  = { fg = "#1e2e1c" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#add4a0", bg = "#1e4868", bold = true }
inactive = { fg = "#1e4868", bg = "#6a9060" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#add4a0", bg = "#1e4868", bold = true }
normal_alt  = { fg = "#1e4868", bg = "#6a9060" }

# Select mode
select_main = { fg = "#add4a0", bg = "#143c52", bold = true }
select_alt  = { fg = "#143c52", bg = "#6a9060" }

# Unset mode
unset_main = { fg = "#add4a0", bg = "#5a2858", bold = true }
unset_alt  = { fg = "#5a2858", bg = "#6a9060" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#1e2e1c" }
perm_type  = { fg = "#1e4868" }
perm_read  = { fg = "#7a4a18" }
perm_write = { fg = "#7a1e18" }
perm_exec  = { fg = "#2a5c22" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#2a5c22", bg = "#3a2860" }
progress_error  = { fg = "#7a4a18", bg = "#7a1e18" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#1e4868" }
active   = { fg = "#5a2858", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#1e4868" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#1e4868" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#1e4868" }
title   = {}
hovered = { fg = "#5a2858", bold = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#6a9060" }
cand            = { fg = "#143c52" }
rest            = { fg = "#1a5858" }
desc            = { fg = "#5a2858" }
separator       = "  "
separator_style = { fg = "#145850" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#143c52" }
run     = { fg = "#5a2858" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#6a9060", bg = "#4a3870" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#1e4868" }
title    = { fg = "#1e4868" }
tbl_col  = { fg = "#143c52" }
tbl_cell = { fg = "#5a2858", bg = "#3a2860" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#2a5c22" }
title_warn  = { fg = "#7a4a18" }
title_error = { fg = "#7a1e18" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#143c52" },
	# Media
	{ mime = "{audio,video}/*", fg = "#7a4a18" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#5a2858" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#2a5c22" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#1a5858" },
	# Fallback
	{ url = "*", fg = "#4a3870" },
	{ url = "*/", fg = "#1e4868" },
]

# : }}}

[icon]

dirs = [
	{ name = ".config", text = "", fg = "#5a2858" },
	{ name = ".git", text = "", fg = "#143c52" },
	{ name = ".github", text = "", fg = "#1e4868" },
	{ name = ".npm", text = "", fg = "#1e4868" },
	{ name = "Desktop", text = "", fg = "#143c52" },
	{ name = "Development", text = "", fg = "#143c52" },
	{ name = "Documents", text = "", fg = "#143c52" },
	{ name = "Downloads", text = "", fg = "#143c52" },
	{ name = "Library", text = "", fg = "#143c52" },
	{ name = "Movies", text = "", fg = "#143c52" },
	{ name = "Music", text = "", fg = "#143c52" },
	{ name = "Pictures", text = "", fg = "#143c52" },
	{ name = "Public", text = "", fg = "#143c52" },
	{ name = "Videos", text = "", fg = "#143c52" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#4a3870" },
	{ if = "link", text = "", fg = "#1e2e1c" },
	{ if = "block", text = "", fg = "#5a2858" },
	{ if = "char", text = "", fg = "#5a2858" },
	{ if = "fifo", text = "", fg = "#5a2858" },
	{ if = "sock", text = "", fg = "#5a2858" },
	{ if = "sticky", text = "", fg = "#5a2858" },
	{ if = "dummy", text = "", fg = "#7a1e18" },

	# Fallback
	{ if = "dir & hovered", text = "", fg = "#1e4868" },
	{ if = "dir", text = "", fg = "#1e4868" },
	{ if = "exec", text = "", fg = "#2a5c22" },
	{ if = "!dir", text = "", fg = "#4a3870" },
]
