# GPU AMD Radeon integrada (ej. ThinkPad L14 Ryzen)
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi

# Wayland / Apps
env = MOZ_WAYLAND_DRM_DEVICE,/dev/dri/renderD128
env = MOZ_DRM_DEVICE,/dev/dri/renderD128

# brightness control
bindle = , XF86MonBrightnessUp, exec, brightnessctl s 5%+
bindle = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
