# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# Some default env vars.

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland
#env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1
env = DISABLE_QT5_COMPAT,0
env = ANKI_WAYLAND,1

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# monitor = DP-1,1366x768@60,0x0,1
# monitor = ,preferred,auto,1
monitor=,highres,auto,1,bitdepth,10
# monitor=,1920x1080@60,0x0,1



# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

input {
  # kb_layout = latam # XKB layout
  kb_layout = us
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  force_no_accel = 1
  # kb_model = cherryblue # XKB model
  # kb_variant = dvorak # XKB variant
  # numlock_by_default = false
  # repeat_rate = 25
  # repeat_delay = 600
  # accel_profile = flat # flat, adaptive
  # natural_scroll = true
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_cancel_ratio = 0.15
}

# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

dwindle {
  no_gaps_when_only = false
  pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = yes # you probably want this
}

master {
    new_is_master = true
}

# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = true
  vrr = 0
  animate_manual_resizes = true
  mouse_move_focuses_monitor = true
  enable_swallow = true
  swallow_regex = ^(wezterm)$
}

# █▀▀ █▄░█ █░█   █░█ ▄▀█ █▀█
# ██▄ █░▀█ ▀▄▀   ▀▄▀ █▀█ █▀▄

source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/nvidia.conf
# source = ~/.config/hypr/intel.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/theme.conf
