env = LIBVA_DRIVER_NAME,iHD
env = VDPAU_DRIVER,va_gl
env = MOZ_WAYLAND_DRM_DEVICE,/dev/dri/renderD129
env = MOZ_DRM_DEVICE,/dev/dri/renderD129

# brightness control

bindle = , XF86MonBrightnessUp, exec, brightnessctl s 400+
bindle = , XF86MonBrightnessDown, exec, brightnessctl s 400-
