# GPU NVIDIA básico
env = LIBVA_DRIVER_NAME,nvidia
env = VDPAU_DRIVER,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

# Vulkan - solo ICD files, sin forzar renderer
env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/nvidia_icd.json
env = VK_DRIVER_FILES,/usr/share/vulkan/icd.d/nvidia_icd.json

# Wayland / Apps
env = MOZ_WAYLAND_DRM_DEVICE,/dev/dri/renderD128
env = MOZ_DRM_DEVICE,/dev/dri/renderD128

# Cursores de software (necesario en NVIDIA)
env = WLR_NO_HARDWARE_CURSORS,1

bindle = , XF86MonBrightnessUp, exec, brightnessctl s 10+
bindle = , XF86MonBrightnessDown, exec, brightnessctl s 10-
