music_dir = ["~/Música"]
loop_mode = "Queue"
volume = 100
speed = 10
add_playlist_front = true
gapless = true
enable_exit_confirmation = false
playlist_display_symbol = true
playlist_select_random_track_quantity = 20
playlist_select_random_album_quantity = 1
theme_selected = "crag"

[album_photo_xywh]
x_between_1_100 = 0
y_between_1_100 = 97
width_between_1_100 = 32
align = "BottomLeft"

[style_color_symbol]
library_foreground = "Foreground"
library_background = "Reset"
library_border = "Red"
library_highlight = "LightYellow"
library_highlight_symbol = "🦄"
playlist_foreground = "Foreground"
playlist_background = "Reset"
playlist_border = "Magenta"
playlist_highlight = "Red"
playlist_highlight_symbol = "🚀"
progress_foreground = "Blue"
progress_background = "Reset"
progress_border = "Cyan"
lyric_foreground = "Foreground"
lyric_background = "Reset"
lyric_border = "Green"

[style_color_symbol.alacritty_theme]
path = ""
name = "crag"
author = "Diego Aguilar"
background = "#1e1e2e"
foreground = "#cdd6f4"
cursor = "#f5e0dc"
text = "#45475a"
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#94e2d5"
white = "#cdd6f4 "
light_black = "#45475a"
light_red = "#eba0ac"
light_green = "#89dceb"
light_yellow = "#f2cdcd"
light_blue = "#74c7ec"
light_magenta = "#b4befe"
light_cyan = "#f5c2e7"
light_white = "#bac2de"
