# vim:ft=kitty
## name:     Forest Green Diff
## blurb:    Diff theme based on the forest-green palette

# text
foreground           #222222
# bg0
background           #add4a0
# fg2 — muted
title_fg             #507848
# bg3
title_bg             #96be8c
margin_bg            #96be8c
# fg1
margin_fg            #1e2e1c
# bg3
filler_bg            #96be8c

# 30% red, 70% bg0
removed_bg           #9dba8e
# 50% red, 50% bg0
highlight_removed_bg #9a8a84
# 40% red, 60% bg0
removed_margin_bg    #9ba796

# 30% green, 70% bg0
added_bg             #8ab88a
# 50% green, 50% bg0
highlight_added_bg   #6e9e6e
# 40% green, 60% bg0
added_margin_bg      #7aaa7a

# bg3
hunk_margin_bg       #96be8c
hunk_bg              #96be8c

# 40% yellow, 60% bg0
search_bg            #a8a878
# fg0
search_fg            #222222

# 40% blue, 60% bg0
select_bg            #7ea0a8
# fg0
select_fg            #222222
