return {
  src = 'https://github.com/catppuccin/nvim',
  data = {
    postload = function()
      local util = require('catppuccin.utils.colors')
      local transparent_background = false
      local clear = {}

      require('catppuccin').setup({
        background = { light = 'latte', dark = 'mocha' },
        dim_inactive = {
          enabled = false,
          shade = 'dark',
          percentage = 0.15,
        },
        transparent_background = transparent_background,
        show_end_of_buffer = false,
        term_colors = true,
        compile_path = vim.fn.stdpath('cache') .. '/catppuccin',
        styles = {
          comments = { 'italic' },
          properties = { 'italic' },
          functions = { 'bold' },
          keywords = { 'italic' },
          operators = { 'bold' },
          conditionals = { 'bold' },
          loops = { 'bold' },
          booleans = { 'bold', 'italic' },
          numbers = {},
          types = {},
          strings = {},
          variables = {},
        },
        integrations = {
          treesitter = true,
          native_lsp = {
            enabled = true,
            virtual_text = {
              errors = { 'italic' },
              hints = { 'italic' },
              warnings = { 'italic' },
              information = { 'italic' },
            },
            underlines = {
              errors = { 'underline' },
              hints = { 'underline' },
              warnings = { 'underline' },
              information = { 'underline' },
            },
          },
          aerial = false,
          alpha = false,
          barbar = false,
          beacon = false,
          blink_cmp = {
            style = 'bordered',
          },
          cmp = false,
          coc_nvim = false,
          dap = true,
          dap_ui = true,
          dashboard = false,
          diffview = true,
          dropbar = { enabled = false },
          fern = false,
          fidget = false,
          flash = true,
          gitgraph = true,
          gitgutter = false,
          gitsigns = true,
          harpoon = true,
          headlines = false,
          hop = false,
          illuminate = true,
          indent_blankline = { enabled = false },
          leap = false,
          lightspeed = false,
          lsp_saga = false,
          lsp_trouble = false,
          markdown = true,
          markview = true,
          mason = true,
          mini = { enabled = false, indentscope_color = 'green' },
          snacks = {
            enabled = true,
            indent_scope_color = 'green',
          },
          navic = { enabled = false },
          neogit = false,
          neotest = true,
          neotree = { enabled = false },
          noice = true,
          notify = true,
          nvim_surround = true,
          nvimtree = false,
          overseer = false,
          pounce = false,
          rainbow_delimiters = true,
          sandwich = false,
          semantic_tokens = true,
          symbols_outline = true,
          telekasten = false,
          treesitter_context = true,
          ts_rainbow = false,
          vim_sneak = false,
          vimwiki = true,
          which_key = true,
        },
        color_overrides = {},
        highlight_overrides = {
          all = function(C)
            return {
              StatusLineGitBranch = {
                fg = C.red,
                style = { 'italic' },
              },
              StatusLineHeader = {
                bg = C.green,
                fg = C.base,
                style = { 'bold' },
              },
              StatusLineHeaderModified = {
                bg = C.red,
                fg = C.base,
                style = { 'italic' },
              },
              StatuslineItalic = { fg = C.text, style = { 'italic' } },
              StatuslineSpinner = { fg = C.green },
              StatuslineTitle = { fg = C.text, style = { 'bold' } },
              StatusLine = { bg = C.base },
              TabLineFill = { bg = C.crust },
              TabLine = { fg = C.overlay0, bg = C.crust },
              BetterTermSymbol = { fg = C.base, bg = C.green },
              TabLineSel = { fg = C.lavender, bg = C.base },
              ['@neorg.lists.unordered.prefix.norg'] = { fg = C.mauve },
              ['@neorg.anchors.declaration.norg'] = { fg = C.blue },
              ['@neorg.headings.1.title.norg'] = { fg = C.pink },
              ['@neorg.headings.1.prefix'] = { fg = C.pink },
              ['@neorg.headings.1.prefix.norg'] = { fg = C.pink },
              ['@neorg.links.location.heading.1.norg'] = { fg = C.pink },
              ['@neorg.headings.2.title.norg'] = { fg = C.yellow },
              ['@neorg.headings.2.prefix'] = { fg = C.yellow },
              ['@neorg.headings.2.prefix.norg'] = { fg = C.yellow },
              ['@neorg.links.location.heading.2.norg'] = { fg = C.yellow },
              ['@neorg.headings.3.title.norg'] = { fg = C.red },
              ['@neorg.headings.3.prefix'] = { fg = C.red },
              ['@neorg.headings.3.prefix.norg'] = { fg = C.red },
              ['@neorg.links.location.heading.3.norg'] = { fg = C.red },
              ['@neorg.headings.4.title.norg'] = { fg = C.sky },
              ['@neorg.headings.4.prefix'] = { fg = C.sky },
              ['@neorg.headings.4.prefix.norg'] = { fg = C.sky },
              ['@neorg.links.location.heading.4.norg'] = { fg = C.sky },
              ['@neorg.headings.5.title.norg'] = { fg = C.green },
              ['@neorg.headings.5.prefix'] = { fg = C.green },
              ['@neorg.headings.5.prefix.norg'] = { fg = C.green },
              ['@neorg.links.location.heading.5.norg'] = { fg = C.green },
              ['@neorg.headings.6.title.norg'] = { fg = C.lavender },
              ['@neorg.headings.6.prefix'] = { fg = C.lavender },
              ['@neorg.headings.6.prefix.norg'] = { fg = C.lavender },
              ['@neorg.links.location.heading.6.norg'] = { fg = C.lavender },
              LspRenamerTitle = { fg = C.base, bg = C.red },
              LspRenamerBorder = { fg = C.red, bg = C.base },
              SnacksTitle = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              SnacksPickerTitle = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              SnacksPickerPreviewTitle = {
                fg = C.green,
                bg = util.blend(C.green, C.surface0, 0.15),
              },
              BlinkCmpMenu = { italic = true, bg = C.surface0 },
              BlinkCmpMenuBorder = { fg = C.crust, bg = C.crust },
              BlinkCmpLabel = { fg = C.subtext0, bg = C.surface0 },
              BlinkCmpLabelMatch = { fg = C.red, bg = C.surface0 },
              BlinkCmpSource = { fg = C.surface2, bg = C.surface0 },
              BlinkCmpMenuSelection = { fg = C.base, bg = C.red },
              BlinkCmpCustomType = { fg = C.lavender, bg = C.surface0 },
              BlinkCmpKindCodeium = {
                fg = C.green,
                bg = util.blend(C.green, C.surface0, 0.15),
              },
              BlinkCmpKindSupermaven = {
                fg = C.pink,
                bg = util.blend(C.pink, C.surface0, 0.15),
              },
              BlinkCmpKindClass = {
                fg = C.yellow,
                bg = util.blend(C.yellow, C.surface0, 0.15),
              },
              BlinkCmpKindColor = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              BlinkCmpKindConstant = {
                fg = C.peach,
                bg = util.blend(C.peach, C.surface0, 0.15),
              },
              BlinkCmpKindConstructor = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindCopilot = {
                fg = C.teal,
                bg = util.blend(C.teal, C.surface0, 0.15),
              },
              BlinkCmpKindEnum = {
                fg = C.green,
                bg = util.blend(C.green, C.surface0, 0.15),
              },
              BlinkCmpKindEnumMember = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              BlinkCmpKindEvent = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindField = {
                fg = C.green,
                bg = util.blend(C.green, C.surface0, 0.15),
              },
              BlinkCmpKindFile = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindFolder = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindFunction = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindInterface = {
                fg = C.yellow,
                bg = util.blend(C.yellow, C.surface0, 0.15),
              },
              BlinkCmpKindKeyword = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              BlinkCmpKindMethod = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindModule = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindOperator = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindProperty = {
                fg = C.green,
                bg = util.blend(C.green, C.surface0, 0.15),
              },
              BlinkCmpKindReference = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              BlinkCmpKindSnippet = {
                fg = C.mauve,
                bg = util.blend(C.mauve, C.surface0, 0.15),
              },
              BlinkCmpKindStruct = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindText = {
                fg = C.red,
                bg = util.blend(C.red, C.surface0, 0.15),
              },
              BlinkCmpKindTypeParameter = {
                fg = C.blue,
                bg = util.blend(C.blue, C.surface0, 0.15),
              },
              BlinkCmpKindUnit = {
                fg = C.green,
                bg = util.blend(C.green, C.surface0, 0.15),
              },
              BlinkCmpKindValue = {
                fg = C.peach,
                bg = util.blend(C.peach, C.surface0, 0.15),
              },
              BlinkCmpKindVariable = {
                fg = C.flamingo,
                bg = util.blend(C.flamingo, C.surface0, 0.15),
              },

              NormalFloat = {
                fg = C.text,
                bg = transparent_background and C.none or C.mantle,
              },
              FloatBorder = {
                fg = transparent_background and C.blue or C.mantle,
                bg = transparent_background and C.none or C.mantle,
              },
              CursorLineNr = { fg = C.green },
              DiagnosticVirtualTextError = { bg = C.none },
              DiagnosticVirtualTextWarn = { bg = C.none },
              DiagnosticVirtualTextInfo = { bg = C.none },
              DiagnosticVirtualTextHint = { bg = C.none },
              LspInfoBorder = { link = 'FloatBorder' },
              MasonNormal = { link = 'NormalFloat' },
              TelescopeMatching = { fg = C.lavender },
              TelescopeResultsDiffAdd = { fg = C.green },
              TelescopeResultsDiffChange = { fg = C.yellow },
              TelescopeResultsDiffDelete = { fg = C.red },
              ['@keyword.return'] = { fg = C.pink, style = clear },
              ['@error.c'] = { fg = C.none, style = clear },
              ['@error.cpp'] = { fg = C.none, style = clear },
            }
          end,
        },
      })
      vim.cmd.colorscheme('catppuccin')
    end,
  },
}
