[ids]

# *
0001:0001
1a2c:8c0e

[main]

shift = oneshot(shift)
leftshift = oneshot(shift)
control = oneshot(control)
alt = oneshot(alt)
altgr = oneshot(altgr)
capslock = overload(control, esc)
space = overload(vimmode, space)
esc = capslock
tab = overload(alt, tab)
semicolon = overload(symbols, semicolon)
a = overload(symbols, a)
leftalt = layer(meta)
meta = oneshot(alt)
w = overload(panel, w)
o = overload(panel, o)
# leftshift = overloadt(alt, oneshot(shift), 250)

[global]
layer_indicator = 1

[vimmode]

q = C-w
w = C-right
e = C-S-right
r = C-y
t = C-t
y = C-c
u = C-z
i = home
o = macro(end enter)
p = C-v
[ = pageup
] = pagedown
a = end
s = S-end
d = C-delete
f = C-=
g = C-home
h = left
j = down
k = up
l = right
; = C-0
' = macro(C-l 50ms C-c 50ms f16 400ms c h r o m i u m 50ms C-v 200ms enter)
z = f11
x = delete
c = macro(home shift end delete)
v = S-right
b = C-left
n = f3
m = macro(C-l 50ms C-c 50ms bookmarks 400ms A-a 10ms)
, = C-S-tab
. = C-tab
/ = C-f

[symbols]

q = @
w = !
e = =
r = S-3
t = %
a = &
s = -
d = $
f = `
g = open
; = macro(scrolllock ~ n)
z = macro(scrolllock ! !)
x = *
v = ^
b = bookmarks
n = back
m = forward
/ = macro(scrolllock ? ?)
[ = (
] = )

[panel]

r = f14
t = macro(f16 400ms k i t t y space 10ms - - c l a s s space 10ms d i a l o g  space 10ms - S-t space h t o p space 10ms h t o p 50ms enter)
i = search
o = email
p = print
a = f13
s = macro(open 400ms I n a o e 50ms enter)
d = M-A-w
f = macro(\ S-9 . * \ S-0)
g = file
h = brightnessdown
j = volumedown
k = volumeup
l = brightnessup
; = find
c = macro(open 400ms k i t t y enter 400ms zsh enter 800ms v i m space S-` / G i t / d o t f i l e s / e t c / k e y d / d e f a u l t . c o n f 50ms enter)
v = f17
b = f18
n = f20
m = mute
, = previoussong
. = nextsong
/ = playpause
space = f15
