[ids]

# *
# Internal keyboard
0001:0001
# RisoPhy PC425
05ac:024f
1a2c:8c0e

[main]

shift = oneshot(shift)
leftshift = oneshot(shift)
control = oneshot(control)
alt = oneshot(alt)
altgr = oneshot(meta)
capslock = overload(control, esc)
esc = capslock
tab = overload(alt, tab)
leftalt = layer(meta)
meta = oneshot(altgr)
space = overload(vimmode, space)
x = overload(panel, x)
z = overload(symbols, z)
semicolon = overload(symbols, semicolon)
/ = overload(panel, /)
apostrophe = overload(control, apostrophe)
# leftshift = overloadt(alt, oneshot(shift), 250)

[global]
layer_indicator = 1

# Layer 1
[vimmode]

backspace = delete
q = C-w
w = C-right
e = C-S-right
r = C-y
t = C-t
y = C-c
u = C-z
i = home
o = macro(end enter)
p = C-v
[ = pageup
] = pagedown
a = end
s = S-end
d = C-delete
f = C-=
g = C-home
h = left
j = down
k = up
l = right
; = C-0
' = macro(C-l 50ms C-c 50ms f16 400ms c h r o m i u m space 50ms C-v 200ms enter)
z = f11
x = delete
c = macro(home S-end delete)
v = S-right
b = C-left
n = f3
m = macro(C-l 50ms C-c 50ms bookmarks 400ms A-a 10ms)
, = C-S-tab
. = C-tab
/ = C-f

# Layer 2
[symbols]

q = @
w = !
e = =
r = S-3
t = %
a = &
s = -
d = $
f = `
g = open
x = *
v = ^
b = bookmarks
n = back
m = forward
[ = (
] = )

# Layer 3
[panel]

t = macro(f16 400ms k i t t y space - - c l a s s space d i a l o g space - S-t space h t o p space h t o p 200ms enter)
i = search
o = email
p = print
a = f13
d = M-A-w
f = macro(M-; 10ms S-a)
g = file
h = brightnessdown
j = volumedown
k = volumeup
l = brightnessup
; = find
c = macro(open 400ms k i t t y 50ms enter 400ms n v i m  100ms space ~ / G i t / d o t f i l e s 100ms / e t c / k e y d 100ms / d e f a u l t . c o n f 50ms enter)
v = f14
b = f18
n = f17
m = mute
, = previoussong
. = nextsong
/ = playpause
space = f15
rightshift = f20
