$rosewater = rgb(c87868)
$rosewaterAlpha = c87868

$flamingo = rgb(c87868)
$flamingoAlpha = c87868

$pink = rgb(b890b0)
$pinkAlpha = b890b0

$mauve = rgb(9090b8)
$mauveAlpha = 9090b8

$red = rgb(c87868)
$redAlpha = c87868

$maroon = rgb(d68878)
$maroonAlpha = d68878

$peach = rgb(c8a870)
$peachAlpha = c8a870

$yellow = rgb(d4b85a)
$yellowAlpha = d4b85a

$green = rgb(88b878)
$greenAlpha = 88b878

$teal = rgb(5ab8a8)
$tealAlpha = 5ab8a8

$sky = rgb(6ab8b0)
$skyAlpha = 6ab8b0

$sapphire = rgb(82aab8)
$sapphireAlpha = 82aab8

$blue = rgb(6a94a8)
$blueAlpha = 6a94a8

$lavender = rgb(9090b8)
$lavenderAlpha = 9090b8

$text = rgb(d0dcc8)
$textAlpha = d0dcc8

$subtext1 = rgb(b8c8b0)
$subtext1Alpha = b8c8b0

$subtext0 = rgb(9aab94)
$subtext0Alpha = 9aab94

$overlay2 = rgb(8a9a88)
$overlay2Alpha = 8a9a88

$overlay1 = rgb(536053)
$overlay1Alpha = 536053

$overlay0 = rgb(3a463a)
$overlay0Alpha = 3a463a

$surface2 = rgb(2d382d)
$surface2Alpha = 2d382d

$surface1 = rgb(263026)
$surface1Alpha = 263026

$surface0 = rgb(202820)
$surface0Alpha = 202820

$base = rgb(1a211a)
$baseAlpha = 1a211a

$mantle = rgb(202820)
$mantleAlpha = 202820

$crust = rgb(263026)
$crustAlpha = 263026
