$rosewater = rgb(d8a8a0)
$rosewaterAlpha = d8a8a0

$flamingo = rgb(d8a8a0)
$flamingoAlpha = d8a8a0

$pink = rgb(5a2858)
$pinkAlpha = 5a2858

$mauve = rgb(3a2860)
$mauveAlpha = 3a2860

$red = rgb(7a1e18)
$redAlpha = 7a1e18

$maroon = rgb(8a2820)
$maroonAlpha = 8a2820

$peach = rgb(7a4a18)
$peachAlpha = 7a4a18

$yellow = rgb(5a4808)
$yellowAlpha = 5a4808

$green = rgb(2a5c22)
$greenAlpha = 2a5c22

$teal = rgb(145850)
$tealAlpha = 145850

$sky = rgb(1a5858)
$skyAlpha = 1a5858

$sapphire = rgb(143c52)
$sapphireAlpha = 143c52

$blue = rgb(1e4868)
$blueAlpha = 1e4868

$lavender = rgb(3a2860)
$lavenderAlpha = 3a2860

$text = rgb(1a1a1a)
$textAlpha = 1a1a1a

$subtext1 = rgb(1e2e1c)
$subtext1Alpha = 1e2e1c

$subtext0 = rgb(3d5c38)
$subtext0Alpha = 3d5c38

$overlay2 = rgb(486040)
$overlay2Alpha = 486040

$overlay1 = rgb(6a9060)
$overlay1Alpha = 6a9060

$overlay0 = rgb(88b07e)
$overlay0Alpha = 88b07e

$surface2 = rgb(96be8c)
$surface2Alpha = 96be8c

$surface1 = rgb(9fc895)
$surface1Alpha = 9fc895

$surface0 = rgb(a4cc98)
$surface0Alpha = a4cc98

$base = rgb(add4a0)
$baseAlpha = add4a0

$mantle = rgb(a4cc98)
$mantleAlpha = a4cc98

$crust = rgb(9fc895)
$crustAlpha = 9fc895
