local key = require('utils.keymap')

key.map('!a', 'cancion', 'canción')
key.map('!a', 'avion', 'avión')
key.map('!a', 'jamon', 'jamón')
key.map('!a', 'ronron', 'ronrón')
key.map('!a', 'moton', 'motón')
key.map('!a', 'balon', 'balón')
key.map('!a', 'camion', 'camión')
key.map('!a', 'sarten', 'sartén')
key.map('!a', 'tiburon', 'tiburón')
key.map('!a', 'cordon', 'cordón')
key.map('!a', 'tacon', 'tacón')
key.map('!a', 'champú', 'champú')
key.map('!a', 'menu', 'menú')
key.map('!a', 'raqui', 'raquí')
key.map('!a', 'aqui', 'aquí')
key.map('!a', 'asi', 'así')
key.map('!a', 'jedi', 'jedí')
key.map('!a', 'frenesi', 'frenesí')
key.map('!a', 'bambu', 'bambú')
key.map('!a', 'iglu', 'iglú')
key.map('!a', 'tabu', 'tabú')
key.map('!a', 'dificil', 'difícil')
key.map('!a', 'util', 'útil')
key.map('!a', 'habil', 'hábil')
key.map('!a', 'joven', 'joven')
key.map('!a', 'imagen', 'imagen')
key.map('!a', 'album', 'álbum')
key.map('!a', 'cardiaco', 'cardíaco')
key.map('!a', 'periodico', 'periódico')
key.map('!a', 'practica', 'práctica')
key.map('!a', 'proximo', 'próximo')
key.map('!a', 'unico', 'único')
key.map('!a', 'fragil', 'frágil')
key.map('!a', 'cesped', 'césped')
key.map('!a', 'character', 'carácter')
key.map('!a', 'esdrujula', 'esdrújula')
key.map('!a', 'pagina', 'página')
key.map('!a', 'practico', 'práctico')
key.map('!a', 'analisis', 'análisis')
key.map('!a', 'pajaro', 'pájaro')
key.map('!a', 'comico', 'cómico')
key.map('!a', 'hippocampo', 'hipocampo')
key.map('!a', 'fantastico', 'fantástico')
key.map('!a', 'electronico', 'electrónico')
key.map('!a', 'paleolitico', 'Paleolítico')
key.map('!a', 'arqueologico', 'arqueológico')
key.map('!a', 'estereofonico', 'estereofónico')
key.map('!a', 'policia', 'policía')
key.map('!a', 'geografia', 'geografía')
key.map('!a', 'biologia', 'biología')
key.map('!a', 'telefono', 'teléfono')
key.map('!a', 'ritmico', 'rítmico')
key.map('!a', 'simbolo', 'símbolo')
key.map('!a', 'ambito', 'ámbito')
key.map('!a', 'catastrofe', 'catástrofe')
key.map('!a', 'didactico', 'didáctico')
key.map('!a', 'helicoptero', 'helicóptero')
key.map('!a', 'comuniquemelo', 'comuníquemelo')
key.map('!a', 'damelo', 'dámelo')
key.map('!a', 'lavandose', 'lavándose')

-- Tilde diacrítica
key.map('!a', 'el', 'él')
key.map('!a', 'tu', 'tú')
key.map('!a', 'mi', 'mí')
key.map('!a', 'si', 'sí')
key.map('!a', 'te', 'té')
key.map('!a', 'de', 'dé')
key.map('!a', 'se', 'sé')
key.map('!a', 'mas', 'más')

-- Interrogativas y exclamativas
key.map('!a', 'que', 'qué')
key.map('!a', 'quien', 'quién')
key.map('!a', 'cual', 'cuál')
key.map('!a', 'como', 'cómo')
key.map('!a', 'donde', 'dónde')
key.map('!a', 'cuando', 'cuándo')
key.map('!a', 'cuanto', 'cuánto')

-- Hiato acentual
key.map('!a', 'pais', 'país')
key.map('!a', 'dia', 'día')
key.map('!a', 'maria', 'maría')
key.map('!a', 'baul', 'baúl')
key.map('!a', 'caida', 'caída')
key.map('!a', 'maiz', 'maíz')
key.map('!a', 'raiz', 'raíz')
key.map('!a', 'rio', 'río')
key.map('!a', 'sonrie', 'sonríe')
key.map('!a', 'oido', 'oído')
key.map('!a', 'grua', 'grúa')
key.map('!a', 'actue', 'actúe')
key.map('!a', 'continue', 'continúe')
key.map('!a', 'fluor', 'flúor')
key.map('!a', 'raul', 'raúl')

-- Esdrújulas
key.map('!a', 'brujula', 'brújula')
key.map('!a', 'celula', 'célula')
key.map('!a', 'plastico', 'plástico')
key.map('!a', 'oceano', 'océano')
key.map('!a', 'oxigeno', 'oxígeno')
key.map('!a', 'musica', 'música')
key.map('!a', 'matematicas', 'matemáticas')
key.map('!a', 'fisica', 'física')
key.map('!a', 'quimica', 'química')
key.map('!a', 'historia', 'história')
key.map('!a', 'filosofia', 'filosofía')
key.map('!a', 'mecanica', 'mecánica')
key.map('!a', 'gramatica', 'gramática')
key.map('!a', 'murcielago', 'murciélago')
key.map('!a', 'miercoles', 'miércoles')
key.map('!a', 'cascara', 'cáscara')
key.map('!a', 'brocoli', 'brócoli')
key.map('!a', 'semaforo', 'semáforo')
key.map('!a', 'parpado', 'párpado')
key.map('!a', 'circulo', 'círculo')
key.map('!a', 'publico', 'público')
key.map('!a', 'ejercito', 'ejército')
key.map('!a', 'numero', 'número')

-- Sobresdrújulas
key.map('!a', 'devuelvemelo', 'devuélvemelo')
key.map('!a', 'entregamelo', 'entrégamelo')
key.map('!a', 'comunicaselo', 'comunícaselo')
key.map('!a', 'corrigemelo', 'corrígemelo')
key.map('!a', 'rapidamente', 'rápidamente')
key.map('!a', 'facilmente', 'fácilmente')
key.map('!a', 'dificilmente', 'difícilmente')

-- Agudas
key.map('!a', 'ademas', 'además')
key.map('!a', 'jamas', 'jamás')
key.map('!a', 'sofa', 'sofá')
key.map('!a', 'cafe', 'café')
key.map('!a', 'bebe', 'bebé')
key.map('!a', 'mama', 'mamá')
key.map('!a', 'papa', 'papá')

-- Graves
key.map('!a', 'arbol', 'árbol')
key.map('!a', 'carcel', 'cárcel')
key.map('!a', 'angel', 'ángel')
key.map('!a', 'tunel', 'túnel')
key.map('!a', 'azucar', 'azúcar')
key.map('!a', 'marmol', 'mármol')
key.map('!a', 'lider', 'líder')


-- Palabras con diéresis
key.map('!a', 'guero', 'güero')
key.map('!a', 'pinguino', 'pingüino')
key.map('!a', 'verguenza', 'vergüenza')
key.map('!a', 'antiguedad', 'antigüedad')
key.map('!a', 'linguistica', 'lingüística')
key.map('!a', 'ciguena', 'cigüeña')
key.map('!a', 'aguita', 'agüita')
key.map('!a', 'paraguero', 'paragüero')
key.map('!a', 'yeguita', 'yegüita')
key.map('!a', 'piraguista', 'piragüista')


