_G.Icons = {
  fillchars = {
    diff = "╱",
    eob = " ",
  },
  listchars = {
    eol = "↲",
    space = "␣",
    tab = "▸ ",
    trail = "▒",
    precedes = "←",
    extends = "→",
    nbsp = "␣",
  },
  diagnostics = {
    bold_error = "",
    error = "",
    bold_warning = "",
    warning = "",
    bold_information = "",
    information = "",
    bold_question = "",
    question = "",
    bold_hint = "",
    hint = "",
    debug = "",
    trace = " ",
  },
  dap = {
    breakpoint = " ",
    breakpoint_condition = " ",
    log_point = " ",
    stopped = " ",
    breakpoint_rejected = " ",
    pause = " ",
    play = " ",
    step_into = " ",
    step_over = " ",
    step_out = " ",
    step_back = " ",
    run_last = " ",
    terminate = " ",
  },
  git = {
    status_added = "",
    status_removed = "",
    status_modified = "",
    topdelete = "﯇",
    changedelete = "",
    untracked = "",
    added = " ",
    deleted = " ",
    renamed = " ",
    ignored = " ",
    unstaged = " ",
    staged = " ",
    conflict = " ",
    Branch = "",
  },
  misc = {
    collapsed = " ",
    expanded = " ",
    current = " ",
    folder_empty = "",
    folder_closed = "",
    folder_open = "",
    file = "",
    v_border = "▐",
  },
}
