[preferred]
default=termfilechooser;gtk
org.freedesktop.impl.portal.FileChooser=termfilechooser
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
org.freedesktop.impl.portal.Inhibit=none
