[preferred]
# El portal de WLR debe ser el JEFE para video
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr

# El portal de GTK debe manejar el diálogo de permisos (micrófono/cámara)
org.freedesktop.impl.portal.Access=gtk
org.freedesktop.impl.portal.Settings=gtk

# Tu selector de archivos por terminal
org.freedesktop.impl.portal.FileChooser=termfilechooser

# Todo lo demás que lo maneje GTK para evitar fallos
default=gtk
