[[mgr.prepend_keymap]]
on   = [ "i" ]
run = "plugin searchjump"
desc = "searchjump mode"

[[mgr.prepend_keymap]]
on   = [ "i" ]
run = "plugin searchjump -- autocd"
desc = "searchjump mode"

[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''', "yank" ]

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "cd /run/media/$USER"
desc = "Go USB"

[[mgr.prepend_keymap]]
on = [ "g", "w" ]
run = "cd ~/Documents/Projects"
desc = "Go Projects"
