# A TOML linter such as https://github.com/tombi-toml/tombi can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "natural"
sort_dir_first = true

[preview]
wrap            = "no"
tab_size        = 2

[[plugin.prepend_previewers]]
mime = "application/epub+zip"
run = "preview-epub"

[[plugin.prepend_preloaders]]
mime = "application/epub+zip"
run = "preview-epub"

[[plugin.prepend_previewers]]
mime = "audio/mpegurl"
run = "code"

[[plugin.prepend_previewers]]
mime = "audio/*"
run = "preview-audio"

[[plugin.prepend_preloaders]]
mime = "audio/mpegurl"
run = "code"

[[plugin.prepend_preloaders]]
mime = "audio/*"
run = "preview-audio"
