#!/bin/bash
#
#
remmina -c $(awk '
/^full address:s:/ { sub("full address:s:",""); sub("\015",""); host=$1; next}
/^username:s:/ { sub("username:s:",""); sub("\015",""); user=$1; next}
END {
  printf "rdp://%s@%s\n", user, host
}
' $1)
